export const CARS_LIST = "CARS_LIST";

export const USERS_LIST = "USERS_LIST";
export const USERS_TOKEN_UNAUTHORIZED = "USERS_TOKEN_UNAUTHORIZED";

export const CAR_SELECT = "CAR_SELECT";
export const CAR_CLEAR = "CAR_CLEAR";
export const CAR_SELECT_ERROR = "CAR_SELECT_ERROR";
